-- Seed the admin-editable catalog. Safe to re-run: existing rows (edited by the admin) are left untouched.
insert into public.site_services (slug, category, title, summary, benefits, demo_slug, icon, sort_order) values
  ('workflow-automation', 'ai-automation', 'Business Workflow Automation', 'We map the repetitive work in your business and turn it into reliable automated workflows.', array['Hours of manual work removed every week','Fewer copy-paste mistakes','Every step logged and traceable']::text[], 'lead-crm-automation', 'flow', 10),
  ('n8n-development', 'ai-automation', 'n8n Workflow Development', 'Production-grade n8n workflows with retries, error alerts and clean documentation.', array['Self-hosted or n8n Cloud','Error handling built in from day one','Handover docs so your team can maintain it']::text[], 'client-hunter', 'nodes', 20),
  ('crm-automation', 'ai-automation', 'CRM Automation & Integrations', 'Connect your CRM, forms, inbox, sheets and calendar so data updates itself.', array['One source of truth for every lead','Automatic status updates','Works with HubSpot, Sheets, Airtable, Supabase and more']::text[], 'lead-crm-automation', 'crm', 30),
  ('lead-followup', 'ai-automation', 'Lead Collection & Follow-up', 'Capture every enquiry and follow up automatically until the lead replies or opts out.', array['No lead left without a reply','Polite, timed follow-ups','Opt-out handling respected']::text[], 'client-hunter', 'target', 40),
  ('reporting', 'ai-automation', 'Automated Reporting & Notifications', 'Daily and weekly reports delivered to email, Slack or WhatsApp without anyone building them.', array['Decisions on fresh numbers','Alerts the moment something changes','No spreadsheet wrangling']::text[], 'analytics-dashboard', 'chart', 50),
  ('monitoring', 'ai-automation', 'Error Handling & Workflow Monitoring', 'Global error handlers, inbox safety nets and alerts so nothing fails silently.', array['Failures surfaced within minutes','Customer messages never lost','Clear logs for every run']::text[], null, 'shield', 60),
  ('business-assistant', 'ai-agents', 'Gemini-powered Business Assistants', 'An AI assistant trained on your approved business information that answers accurately.', array['Answers from your own knowledge','Hands over to a human when unsure','Never invents prices or facts']::text[], 'clinic-ai-receptionist', 'spark', 70),
  ('support-agent', 'ai-agents', 'AI Customer Support Agents', 'Resolve common questions instantly on your website, WhatsApp and social inboxes.', array['Replies in seconds, 24/7','Consistent tone in many languages','Escalation to your team']::text[], 'ecommerce-support', 'chat', 80),
  ('lead-qualification', 'ai-agents', 'AI Lead Qualification', 'The agent asks the right questions, scores the lead and routes hot buyers to your sales team.', array['Sales time spent on serious buyers','Structured lead data in your CRM','Instant Slack or email alerts']::text[], 'skyline-whatsapp-bot', 'filter', 90),
  ('appointment-agent', 'ai-agents', 'AI Appointment Booking', 'Customers pick a real free slot, get a confirmation and an automatic reminder.', array['Fewer no-shows','Bookings outside office hours','Synced with your calendar']::text[], 'appointment-booking', 'calendar', 100),
  ('voice-receptionist', 'ai-agents', 'AI Voice Receptionists', 'A natural-sounding phone agent that answers calls, qualifies callers and books visits.', array['No missed calls','Call summaries in your CRM','Transfers to a human on request']::text[], 'skyline-voice-receptionist', 'phone', 110),
  ('messaging-assistant', 'ai-agents', 'Website & Messaging Assistants', 'One AI brain across your website chat, WhatsApp Business, Instagram and Facebook.', array['Same answers on every channel','Official WhatsApp Business API','Lead capture built in']::text[], 'skyline-whatsapp-bot', 'whatsapp', 120),
  ('business-websites', 'web-software', 'Premium Business Websites', 'Fast, beautiful, mobile-first websites that are built to convert visitors into enquiries.', array['Designed for your audience','SEO-ready structure','AI chat and booking built in']::text[], 'web-design-showcase', 'globe', 130),
  ('ecommerce', 'web-software', 'E-commerce Platforms', 'Online stores with automated order updates, support and inventory sync.', array['Order status answered automatically','Inventory alerts','Payment-provider ready']::text[], 'ecommerce-support', 'cart', 140),
  ('web-apps', 'web-software', 'Custom Web Applications', 'Bespoke tools for the way your team works, from intake forms to full platforms.', array['Built around your process','Secure logins and roles','Scales as you grow']::text[], 'web-app-admin', 'code', 150),
  ('crm-erp', 'web-software', 'CRM & ERP Systems', 'Lightweight CRM and ERP systems for leads, customers, stock and invoices.', array['Only the features you need','Automations connected','Reports in one click']::text[], 'web-app-admin', 'grid', 160),
  ('hospital-management', 'web-software', 'Hospital & Clinic Management Systems', 'Patients, appointments, reminders and front-desk AI in one system.', array['Front desk load reduced','Reminders cut no-shows','Role-based access to records']::text[], 'clinic-ai-receptionist', 'plus', 170),
  ('portals-dashboards', 'web-software', 'Customer Portals & Admin Dashboards', 'Secure portals for customers and live dashboards for owners.', array['Customers self-serve','Owners see the numbers daily','Data protected by row-level security']::text[], 'analytics-dashboard', 'layout', 180),
  ('social-automation', 'growth-automation', 'Social Media Workflow Automation', 'Auto-replies to comments and DMs, scheduled posting and lead capture from social.', array['Every comment answered','Leads moved to DMs and CRM','Consistent brand voice']::text[], 'facebook-auto-reply', 'share', 190),
  ('content-pipelines', 'growth-automation', 'Content Generation & Publishing', 'AI-assisted content pipelines that draft, design, approve and publish on schedule.', array['Weeks of content prepared in hours','Human approval step','Published to all channels']::text[], 'social-media-workflow', 'pen', 200),
  ('inquiry-management', 'growth-automation', 'Customer Inquiry Management', 'Every enquiry from every channel in one inbox, tagged, prioritised and answered.', array['Nothing slips through','Faster first response','Clear ownership']::text[], 'lead-crm-automation', 'inbox', 210),
  ('sales-pipeline', 'growth-automation', 'Sales Pipeline Automation', 'Prospecting, personalised outreach and follow-up sequences that run every day.', array['A steady flow of qualified prospects','Personalised at scale','Daily sending limits for deliverability']::text[], 'client-hunter', 'funnel', 220),
  ('email-messaging', 'growth-automation', 'Email & Messaging Integrations', 'Gmail, Outlook, WhatsApp Business, Slack and SMS connected to your workflows.', array['Messages sent from the right inbox','Templates with personalisation','Delivery tracked']::text[], null, 'mail', 230)
on conflict (slug) do nothing;

insert into public.site_demos (slug, title, category, summary, use_case, tags, featured, sort_order) values
  ('skyline-voice-receptionist', 'Skyline AI Voice Receptionist', 'Voice AI · Real estate', 'A phone agent for Skyline Properties (Dubai) that answers calls, qualifies buyers and books viewings.', 'Agencies that miss calls after hours or during viewings. The agent answers in seconds, asks budget, area and timeline, books a viewing and posts the lead to the CRM and Slack.', array['Vapi','n8n','Google Sheets','Slack']::text[], true, 10),
  ('skyline-whatsapp-bot', 'Skyline WhatsApp AI Chatbot', 'WhatsApp · Real estate', 'The Skyline Properties WhatsApp agent: searches listings, qualifies the lead and alerts the sales team.', 'Property enquiries arrive on WhatsApp at all hours. The agent answers from the listings knowledge base, qualifies the buyer and saves the lead.', array['WhatsApp Business API','n8n','Pinecone','Gmail']::text[], true, 20),
  ('clinic-ai-receptionist', 'Clinic AI Receptionist', 'Healthcare', 'A front-desk assistant for clinics that books appointments, answers FAQs and routes medical questions to staff.', 'Clinics lose patients when phones ring out. The assistant books, reschedules and reminds, while anything medical goes to a human.', array['Booking','Reminders','Human handoff']::text[], true, 30),
  ('client-hunter', 'Client Hunter: n8n Lead Engine', 'Lead generation · n8n', 'Our real n8n workflow that finds businesses, researches them, writes a personalised email and fills the outreach sheet.', 'Agencies and B2B sellers who need a steady, quality list of prospects every morning without manual research.', array['n8n','Google Maps data','OpenAI','Google Sheets','Gmail']::text[], true, 40),
  ('facebook-auto-reply', 'Facebook Auto-Comment Reply', 'Social media', 'A 5-second short: comments on a post get an instant, on-brand reply and the lead moves to DM.', 'Pages running ads get hundreds of ''price?'' comments. Every comment gets a helpful reply and a private message in seconds.', array['Meta Graph API','n8n','AI replies']::text[], true, 50),
  ('web-design-showcase', 'Website Design Showcase', 'Web design', 'Three live demo websites we designed: a real estate portal and two skin clinics, each with AI built in.', 'Businesses that need a modern website that books, answers and captures leads, not just a brochure.', array['Responsive','SEO','AI chat','Booking']::text[], true, 60),
  ('web-app-admin', 'Web Development: AI Front-Desk Admin', 'Web development', 'A custom admin app with KPIs, CRM sheet, reminders and conversation history.', 'Owners who want to see every conversation, booking and follow-up in one secure dashboard.', array['Dashboard','CRM','Reminders']::text[], false, 70),
  ('appointment-booking', 'Appointment Booking Automation', 'Booking', 'Pick a service, a real free slot and get a confirmation plus reminder automatically.', 'Salons, clinics and consultants who want bookings 24/7 without double-booking.', array['Calendar','Reminders','WhatsApp']::text[], false, 80),
  ('ecommerce-support', 'E-commerce Customer Support', 'E-commerce', 'Order tracking, returns and product questions answered instantly with a handoff to staff.', 'Online stores drowning in ''where is my order'' messages.', array['Order lookup','Returns','Handoff']::text[], false, 90),
  ('lead-crm-automation', 'Lead Generation & CRM Automation', 'CRM', 'Leads from every channel land in one pipeline, get scored and move stage by stage automatically.', 'Teams whose leads are scattered across WhatsApp, forms and inboxes.', array['Pipeline','Scoring','Alerts']::text[], false, 100),
  ('social-media-workflow', 'Automated Social Media Workflow', 'Content', 'Idea to published post: AI drafts, designs, waits for approval and publishes to every channel.', 'Founders with no time to post consistently on LinkedIn, Instagram and Facebook.', array['Carousels','Approval','Scheduling']::text[], false, 110),
  ('analytics-dashboard', 'Business Analytics Dashboard', 'Analytics', 'A live owner dashboard: leads, bookings, revenue and response times on one screen.', 'Owners who want daily numbers without opening five tools.', array['KPIs','Funnels','Daily report']::text[], false, 120)
on conflict (slug) do nothing;

-- Emails listed here become admins automatically when their Supabase Auth user is created.
insert into public.site_admin_allowlist (email) values ('fahdzafar73@gmail.com') on conflict do nothing;
